export const ADD_INGRE = "ADD_INGRE";
export const RM_INGRE = "RM_INGRE";
export const SET_INGRE = "SET_INGRE";
export const FETCH_INGR_ERROR = "FETCH_INGR_ERROR";
export const Fetch_INGRE_START = "Fetch_INGRE_START";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";
export const BURGER_PURCHASE_INIT = "BURGER_PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";



export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_INIT_LOGOUT = "AUTH_INIT_LOGOUT";
export const AUTH_INIT_TIMEOUT_LOGOUT = "AUTH_INIT_TIMEOUT_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REDIRECT = "AUTH_REDIRECT";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
